### ISSUE TITLE
Data augmentation issues

### ISSUE THREAD

**Issue by ccl-private** [mangoggul/yolo_multi_modal_modify#2]
![image](https://github.com/user-attachments/assets/85a3e271-33cf-41cb-ae6a-f7082e326ec6)
I noticed that you enhanced each of the 3 imgs in ultralytics/data/base.py vim “img1, tmp , tmp2=self.transforms(img1), self.transforms(tmp), self.transforms(tmp2)“. The self.transforms is from here.
![image](https://github.com/user-attachments/assets/503f2dda-92f3-4fce-bb00-b0b3c1c6f70a)
As far as I know, the random enhancement parameters of the three images are different, which means that the enhancement of the three images with the same input is different.

**Comment by mangoggul** [comment]
Your right.
For code Implentation. i made dummy for it. 
Can you fix this part?..

**Comment by ccl-private** [comment]
try this.
```
import torch


def __getitem__(self, index):
    """Returns transformed label information for given index."""
    img1,img2,img3= self.get_image_and_label(index)
    tmp = deepcopy(img1)
    tmp['img'] = img2['img']
    tmp2 = deepcopy(img1)
    tmp2['img'] = img3['img']
    
    seed = torch.randint(0, 2**32, (1,)).item()
    torch.manual_seed(seed)
    img1 =self.transforms(img1)
    torch.manual_seed(seed)
    tmp = self.transforms(tmp)
    torch.manual_seed(seed)
    tmp2 = self.transforms(tmp2)
    img1['img2'] = tmp['img']
    img1['img3'] = tmp2['img']
    return img1
```

**Comment by ccl-private** [comment]
A better solution is to regard the three images as one multispectral image, so that they can be enhanced at once and then disassembled after enhancement.
https://blog.csdn.net/Lizongming_/article/details/135652383

**Comment by mangoggul** [comment]
Thanks for Suggestion. I'll consider it.
